# Generated by Django 4.2.27 on 2026-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(db_index=True, verbose_name="booking date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["venue", "booking_date", "status"], name="booking_venue_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user", "booking_date"], name="booking_user_date_idx"),
        ),
    ]
